# Generated by Django 3.0.5 on 2025-01-23 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0005_claim_claimrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimrecord',
            name='Claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.Claim'),
        ),
    ]
